### ISSUE TITLE
User forms are broken

### ISSUE THREAD

**Issue by Christian24** [FancyGoldfish07/Fachschaft#3]
My user forms have no layout anymore and the registration form shows a weird textbox at the very end. 
![bildschirmfoto 2016-02-22 um 14 23 28](https://cloud.githubusercontent.com/assets/2406635/13219398/13878d10-d970-11e5-9fc1-e4f414881069.png)

**Comment by Christian24** [comment]
This seems to apply to all forms with old styling, such as Admin user controls. Some weird angularJS it seems: <input id="textAngular-editableFix-010203040506070809" class="ta-hidden-input" aria-hidden="true" unselectable="on" tabindex="-1">

**Comment by FancyGoldfish07** [comment]
Is this still a thing?
Because I think we should start getting rid of this part of the old design.
And because the new design bases on bootstrap I think the designers custom css and js files could/should also be removed.

**Comment by Christian24** [comment]
No we fixed it with our design now.
